- name: installing Nginx
  ansible.builtin.package:
    name: nginx
    state: present
- name: Nginx services
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  
- name: remove old existing code
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: create html file
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name : download the code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: extract the file
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy expense cong
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
    remore_src: yes
    

- name: restart service
  ansible.builtin.service:
    name: nginx
    state: restarted
