- name: remove the existing file
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent
  ignore_errors: true

- name: make dir
  ansible.builtin.file:
  path: "{{ app_location }}"
  state: directory

- name: download application code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: "{{ app_location }}"
    remote_sec: true

