tasks: 
- name: installing python packages
  ansible.builtin.pip: 
    name: 
    - PyMySQL
    executable: pip3.9

- name: install mysql
  ansible.builtin.package:
    name: mysql-server
    state: present
- name: services 
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
  
#  